version: "3.9"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER: mysqluser
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: simple_journal_entry_db
    restart: always
    ports:
#      - ${MYSQL_PORT}:3306
      - "3306:3306"
    volumes:
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/store:/var/lib/mysql
      - ./docker/mysql/log:/var/log/mysql